"""Original house pack: stable, short questions and prompts for a living-room crowd."""
HOUSE = [
    ("Screen time", "In Shrek, what kind of creature is Donkey's love interest?", "Dragon", "Ogre", "Unicorn", "Fairy"),
    ("Food fight", "Which cheese is traditionally used in a Greek salad?", "Feta", "Brie", "Cheddar", "Gouda"),
    ("Mixtape", "Which band released 'Dancing Queen'?", "ABBA", "Queen", "Fleetwood Mac", "Blondie"),
    ("Wild world", "How many hearts does an octopus have?", "Three", "One", "Two", "Eight"),
    ("Game on", "In basketball, how many points is a free throw worth?", "One", "Two", "Three", "Four"),
    ("Screen time", "What is the name of the cowboy toy in Toy Story?", "Woody", "Buzz", "Andy", "Rex"),
    ("Food fight", "Which fruit gives guacamole its green color?", "Avocado", "Lime", "Kiwi", "Green tomato"),
    ("Wild world", "Which planet is famous for its prominent rings?", "Saturn", "Mars", "Venus", "Mercury"),
    ("Mixtape", "Who released the album 'Lemonade' in 2016?", "Beyoncé", "Rihanna", "Adele", "Lady Gaga"),
    ("Game on", "Which chess piece moves in an L shape?", "Knight", "Bishop", "Rook", "Queen"),
    ("Screen time", "In Friends, what is the coffee shop called?", "Central Perk", "Daily Grind", "Central Park", "Bean There"),
    ("Wild world", "What is the largest ocean on Earth?", "Pacific", "Atlantic", "Indian", "Arctic"),
    ("Food fight", "What type of pasta is shaped like little bow ties?", "Farfalle", "Penne", "Fusilli", "Linguine"),
    ("Mixtape", "Which instrument typically has 88 keys?", "Piano", "Violin", "Trumpet", "Flute"),
    ("Game on", "In bowling, what is three strikes in a row called?", "Turkey", "Eagle", "Hat trick", "Triple double"),
    ("Screen time", "What color pill does Neo take in The Matrix?", "Red", "Blue", "Green", "White"),
    ("Wild world", "Which animal is the tallest living land animal?", "Giraffe", "Elephant", "Ostrich", "Camel"),
    ("Food fight", "What is the main ingredient in hummus?", "Chickpeas", "Lentils", "Potatoes", "White beans"),
    ("Mixtape", "Which singer is known as the 'Rocket Man'?", "Elton John", "David Bowie", "Billy Joel", "Sting"),
    ("Game on", "In tennis scoring, what does 'love' mean?", "Zero", "A tie", "Match point", "An ace"),
    ("Screen time", "What is the name of Batman's home city?", "Gotham", "Metropolis", "Wakanda", "Smallville"),
    ("Wild world", "How many sides does a hexagon have?", "Six", "Five", "Seven", "Eight"),
    ("Food fight", "Sushi rice is traditionally seasoned with which ingredient?", "Rice vinegar", "Soy sauce", "Sesame oil", "Coconut milk"),
    ("Mixtape", "Which group sang 'Wannabe' in 1996?", "Spice Girls", "TLC", "Destiny's Child", "All Saints"),
    ("Game on", "How many players from one volleyball team are on court in indoor volleyball?", "Six", "Five", "Seven", "Eight"),
    ("Screen time", "In Finding Nemo, what kind of fish is Nemo?", "Clownfish", "Goldfish", "Angelfish", "Swordfish"),
    ("Wild world", "Which gas do plants absorb during photosynthesis?", "Carbon dioxide", "Oxygen", "Helium", "Hydrogen"),
    ("Food fight", "Which country is the origin of the dish paella?", "Spain", "Italy", "Mexico", "Greece"),
    ("Mixtape", "What was Freddie Mercury's band?", "Queen", "The Beatles", "Oasis", "The Police"),
    ("Game on", "What color jersey is worn by the Tour de France's overall leader?", "Yellow", "Red", "Blue", "Green"),
    ("Screen time", "Which movie features the song 'Let It Go'?", "Frozen", "Tangled", "Moana", "Brave"),
    ("Wild world", "What is the chemical symbol for gold?", "Au", "Ag", "Go", "Gd"),
]
DRAW = ["pizza", "roller coaster", "penguin", "karaoke", "astronaut", "campfire", "mermaid", "skateboard", "birthday cake", "hot dog", "tornado", "giraffe", "washing machine", "pirate", "snowman", "unicorn", "dentist", "helicopter", "disco ball", "cactus", "zombie", "sunglasses", "popcorn", "bicycle", "jellyfish", "superhero", "lighthouse", "treadmill", "pancakes", "scarecrow", "robot", "hammock"]
RIFF = [
    "The worst possible name for a dating app.",
    "A terrible thing to hear from your Uber driver.",
    "The real reason aliens haven't visited us.",
    "A rejected slogan for this friend group.",
    "The most useless superpower you could have.",
    "A ridiculous item on a billionaire's grocery list.",
    "The title of a documentary about tonight.",
    "The worst thing to put on a wedding invitation.",
    "A new Olympic sport everyone in this room could enter.",
    "The one thing a haunted house should never have.",
    "A suspiciously specific rule at an all-you-can-eat buffet.",
    "An honest name for your group chat.",
]
