// The show's sound. Music is a composed score (controller/public/assets/audio, generated by
// controller/scripts/audio): a loop per phase, crossfaded, ducked under stingers, with a hurry-up bed for the
// last ten seconds. Effects play from samples with a little pitch jitter; any effect without a sample falls back
// to a small synthesized version so the show never goes silent. There is no synthesized music.
// Buses: sfx and music feed master. Character sits in 300Hz–5kHz because TV speakers have no bass.

let ctx: AudioContext | null = null
let master: GainNode, sfxBus: GainNode, musicBus: GainNode, duckBus: GainNode
let noiseBuf: AudioBuffer

/** [spotify]: Spotify on the Mac plays under the show instead of the score (effects still play). */
export interface Mix { on: boolean; music: number; sfx: number; spotify: boolean }
const KEY = 'partyos.tv.mix'
const DEFAULT_MIX: Mix = { on: true, music: 0.6, sfx: 0.9, spotify: false }
export function loadMix(): Mix {
  try { return { ...DEFAULT_MIX, ...JSON.parse(localStorage.getItem(KEY) ?? '{}') } } catch { return { ...DEFAULT_MIX } }
}
let mix = loadMix()

export function setMix(m: Mix) {
  mix = m
  try { localStorage.setItem(KEY, JSON.stringify(m)) } catch { /* private mode */ }
  if (!ctx) return
  const t = ctx.currentTime
  master.gain.setTargetAtTime(m.on ? 0.9 : 0, t, 0.05)
  musicBus.gain.setTargetAtTime(m.spotify ? 0 : m.music * 0.7, t, 0.05)
  sfxBus.gain.setTargetAtTime(m.sfx, t, 0.05)
}

/** Creates/resumes the context and starts loading the sample bank. Must run inside a user gesture unless Chrome allows autoplay. */
export function unlockAudio(): boolean {
  if (!ctx) {
    ctx = new AudioContext({ latencyHint: 'interactive' })
    const comp = ctx.createDynamicsCompressor()
    comp.threshold.value = -12; comp.ratio.value = 3; comp.attack.value = 0.004; comp.release.value = 0.25
    comp.connect(ctx.destination)
    master = ctx.createGain(); master.connect(comp)
    sfxBus = ctx.createGain(); sfxBus.connect(master)
    musicBus = ctx.createGain(); musicBus.connect(master)
    duckBus = ctx.createGain(); duckBus.connect(musicBus)
    noiseBuf = ctx.createBuffer(1, ctx.sampleRate * 2, ctx.sampleRate)
    const d = noiseBuf.getChannelData(0)
    for (let i = 0; i < d.length; i++) d[i] = Math.random() * 2 - 1
    setMix(mix)
    void loadBank()
  }
  if (ctx.state !== 'running') void ctx.resume()
  return ctx.state === 'running'
}
export const audioRunning = () => ctx?.state === 'running'

const midi = (m: number) => 440 * Math.pow(2, (m - 69) / 12)
const jitter = (amount = 0.04) => 1 + (Math.random() * 2 - 1) * amount
const semis = (n: number) => Math.pow(2, n / 12)

// ---------- the sample bank ----------

interface MusicTrack { file: string; gain?: number; loopStart?: number; loopEnd?: number }
interface Manifest { sfx: Record<string, string[]>; music: Record<string, MusicTrack> }
const BASE = '/assets/audio/'
const sfxBank = new Map<string, AudioBuffer[]>()
const musicBank = new Map<string, { buf: AudioBuffer; track: MusicTrack }>()
const rotation = new Map<string, number>()

async function fetchBuffer(file: string): Promise<AudioBuffer | null> {
  try {
    const r = await fetch(BASE + file)
    if (!r.ok || !(r.headers.get('content-type') ?? '').startsWith('audio')) return null
    return await ctx!.decodeAudioData(await r.arrayBuffer())
  } catch { return null }
}

async function loadBank() {
  let manifest: Manifest
  try {
    const r = await fetch(BASE + 'manifest.json')
    if (!r.ok) return
    manifest = await r.json()
  } catch { return }
  // Music first for the phase we're in, then everything else; effects in parallel.
  await Promise.all(Object.entries(manifest.sfx ?? {}).map(async ([id, files]) => {
    const bufs = (await Promise.all(files.map(fetchBuffer))).filter((b): b is AudioBuffer => !!b)
    if (bufs.length) sfxBank.set(id, bufs)
  }))
  const order = Object.entries(manifest.music ?? {}).sort(([a], [b]) => (a === want ? -1 : b === want ? 1 : 0))
  for (const [mode, track] of order) {
    const buf = await fetchBuffer(track.file)
    if (buf) { musicBank.set(mode, { buf, track }); if (mode === want || mode === MUSIC_FALLBACK[want] || (mode === 'hurry' && hurry)) retune() }
  }
}

/** Plays a sample by id (round-robin through its variants), or runs [fallback] if there is none. */
function play(id: string, opts: { rate?: number; gain?: number; delay?: number } = {}, fallback?: () => void) {
  if (!ctx) return
  const bufs = sfxBank.get(id)
  if (!bufs) { fallback?.(); return }
  const i = (rotation.get(id) ?? 0) % bufs.length
  rotation.set(id, i + 1)
  const src = ctx.createBufferSource()
  src.buffer = bufs[i]
  src.playbackRate.value = (opts.rate ?? 1) * jitter(0.03)
  const g = ctx.createGain()
  g.gain.value = opts.gain ?? 1
  src.connect(g); g.connect(sfxBus)
  src.start(ctx.currentTime + 0.005 + (opts.delay ?? 0))
}

/** Dips the music under a stinger. */
function duck(depth = 0.35, holdSec = 1.2) {
  if (!ctx) return
  const t = ctx.currentTime
  duckBus.gain.cancelScheduledValues(t)
  duckBus.gain.setTargetAtTime(depth, t, 0.03)
  duckBus.gain.setTargetAtTime(1, t + holdSec, 0.35)
}

// ---------- synth voices (effect fallbacks only) ----------

interface ToneOpts { type?: OscillatorType; gain?: number; attack?: number; release?: number; slideTo?: number; bus?: GainNode; lp?: number; detune?: number }
function tone(freq: number, t: number, dur: number, o: ToneOpts = {}) {
  if (!ctx) return
  const osc = ctx.createOscillator()
  osc.type = o.type ?? 'sine'
  osc.frequency.setValueAtTime(freq, t)
  if (o.detune) osc.detune.value = o.detune
  if (o.slideTo) osc.frequency.exponentialRampToValueAtTime(o.slideTo, t + dur)
  const g = ctx.createGain()
  const peak = o.gain ?? 0.2
  const a = o.attack ?? 0.005
  g.gain.setValueAtTime(0.0001, t)
  g.gain.exponentialRampToValueAtTime(peak, t + a)
  g.gain.exponentialRampToValueAtTime(0.0001, t + dur + (o.release ?? 0.05))
  let out: AudioNode = g
  osc.connect(g)
  if (o.lp) {
    const f = ctx.createBiquadFilter(); f.type = 'lowpass'; f.frequency.value = o.lp
    g.connect(f); out = f
  }
  out.connect(o.bus ?? sfxBus)
  osc.start(t); osc.stop(t + dur + (o.release ?? 0.05) + 0.02)
}

interface NoiseOpts { gain?: number; type?: BiquadFilterType; freq?: number; q?: number; sweepTo?: number; attack?: number; bus?: GainNode }
function noise(t: number, dur: number, o: NoiseOpts = {}) {
  if (!ctx) return
  const src = ctx.createBufferSource()
  src.buffer = noiseBuf
  const f = ctx.createBiquadFilter()
  f.type = o.type ?? 'bandpass'; f.frequency.setValueAtTime(o.freq ?? 2000, t); f.Q.value = o.q ?? 1
  if (o.sweepTo) f.frequency.exponentialRampToValueAtTime(o.sweepTo, t + dur)
  const g = ctx.createGain()
  g.gain.setValueAtTime(0.0001, t)
  g.gain.exponentialRampToValueAtTime(o.gain ?? 0.2, t + (o.attack ?? 0.003))
  g.gain.exponentialRampToValueAtTime(0.0001, t + dur)
  src.connect(f); f.connect(g); g.connect(o.bus ?? sfxBus)
  src.start(t, Math.random()); src.stop(t + dur + 0.02)
}

function brass(ms: number[], t: number, dur: number, gain = 0.07, bus = sfxBus) {
  ms.forEach((m) => {
    tone(midi(m), t, dur, { type: 'sawtooth', gain, attack: 0.02, release: 0.12, lp: 2600, bus, detune: -6 })
    tone(midi(m), t, dur, { type: 'sawtooth', gain: gain * 0.7, attack: 0.02, release: 0.12, lp: 2600, bus, detune: 7 })
  })
}
const kick = (t: number, g = 0.35, bus = sfxBus) => tone(120, t, 0.18, { gain: g, slideTo: 45, bus })
const block = (m: number, t: number, g = 0.12, bus = sfxBus) => { tone(midi(m), t, 0.05, { gain: g, bus }); noise(t, 0.02, { freq: midi(m) * 2, q: 8, gain: g * 0.5, bus }) }

// ---------- effects ----------

const penta = [0, 2, 4, 7, 9]
const scaleStep = (root: number, step: number) => root + penta[step % 5] + 12 * Math.floor(step / 5)
const T = () => (ctx ? ctx.currentTime + 0.01 : 0)

/** Synthesized fallbacks, kept for any effect the sample bank lacks. */
const synth = {

  /** Lightest tier: moving focus. */
  focus() { tone(1700 * jitter(), T(), 0.03, { gain: 0.05 }) },
  /** Middle tier: choosing something. */
  select() { const t = T(); tone(220, t, 0.12, { type: 'triangle', gain: 0.25, slideTo: 110 }); noise(t, 0.03, { freq: 3000, gain: 0.08 }) },
  back() { noise(T(), 0.18, { freq: 2500, sweepTo: 500, q: 2, gain: 0.12 }) },
  /** A contestant joins: a xylophone note one step higher each time. */
  join(step: number) {
    const t = T(); const f = midi(scaleStep(72, step % 12))
    tone(f, t, 0.35, { gain: 0.22 }); tone(f * 4, t, 0.08, { gain: 0.06 }); tone(f * 2.76, t, 0.12, { gain: 0.05 })
  },
  leave() { tone(midi(64), T(), 0.25, { type: 'triangle', gain: 0.12, slideTo: midi(57) }) },
  /** A bluff or pick is in: a poker-chip clink that climbs with progress. */
  chip(step: number) {
    const t = T(); const f = 2000 * Math.pow(2, Math.min(step, 16) / 16) * jitter(0.02)
    tone(f, t, 0.06, { gain: 0.12 }); tone(f * 1.48, t + 0.035, 0.07, { gain: 0.09 }); noise(t, 0.02, { type: 'highpass', freq: 5000, gain: 0.08 })
  },
  /** One card dealt onto the table. */
  deal(step: number) { const t = T(); noise(t, 0.07, { freq: 2600 + step * 180, q: 1.5, sweepTo: 5000, gain: 0.2 }); tone(300 + step * 20, t, 0.03, { gain: 0.06 }) },
  ding() { const t = T(); tone(1318, t, 0.5, { gain: 0.18 }); tone(1318 * 2.01, t, 0.2, { gain: 0.05 }) },
  allIn() { const t = T(); [0, 0.14].forEach((d, i) => { tone(i ? 1760 : 1318, t + d, 0.55, { gain: 0.2 }); tone((i ? 1760 : 1318) * 3, t + d, 0.1, { gain: 0.04 }) }) },
  buzzer() { const t = T(); tone(110, t, 0.7, { type: 'square', gain: 0.1, lp: 1400 }); tone(117, t, 0.7, { type: 'square', gain: 0.1, lp: 1400 }) },
  /** Last five seconds: woodblock tick-tock that rises at 3-2-1. */
  tick(secondsLeft: number) { block(secondsLeft <= 3 ? 84 + (3 - secondsLeft) * 2 : secondsLeft % 2 ? 79 : 76, T(), 0.2, sfxBus) },
  /** Round-start band hit. */
  roundStart(final = false) {
    const t = T(); const root = final ? 62 : 60
    brass([root, root + 4, root + 7, root + 11], t, 0.35, 0.06); brass([root + 12, root + 16], t + 0.18, 0.5, 0.05)
    kick(t, 0.4, sfxBus); noise(t, 0.6, { type: 'highpass', freq: 5000, gain: 0.1 })
  },
  /** The show opens: a two-part fanfare. */
  showOpen() {
    const t = T()
    ;[[60, 64, 67], [62, 65, 69], [64, 67, 72]].forEach((ch, i) => brass(ch, t + i * 0.16, 0.14, 0.05))
    brass([65, 69, 72, 77], t + 0.52, 0.8, 0.06); kick(t + 0.52, 0.4, sfxBus); noise(t + 0.52, 1.2, { type: 'highpass', freq: 4500, gain: 0.12 })
  },
  drumroll(sec = 1.6) {
    const t = T(); const n = Math.floor(sec * 28)
    for (let i = 0; i < n; i++) noise(t + i / 28, 0.05, { freq: 900, q: 0.7, gain: 0.03 + 0.1 * (i / n) })
  },
  crash() { noise(T(), 1.6, { type: 'highpass', freq: 3500, gain: 0.22 }) },
  /** Wah-wah trombone for a fake that fooled people. */
  womp() {
    const t = T()
    ;[[63, 0], [62, 0.28], [61, 0.56]].forEach(([m, d]) => tone(midi(m), t + d, 0.24, { type: 'sawtooth', gain: 0.1, lp: 900, attack: 0.03 }))
    tone(midi(60), t + 0.84, 0.7, { type: 'sawtooth', gain: 0.1, lp: 700, attack: 0.03, slideTo: midi(58) })
  },
  /** Studio audience "ooooh": detuned low voices sliding up, then down. Bigger crowd = more fooled. */
  ooh(size: number) {
    if (!ctx) return
    const t = T(); const voices = Math.min(3 + size * 2, 12)
    for (let i = 0; i < voices; i++) {
      const f = 190 * jitter(0.18); const o = ctx.createOscillator(); o.type = 'sawtooth'
      o.frequency.setValueAtTime(f, t); o.frequency.linearRampToValueAtTime(f * 1.35, t + 0.45); o.frequency.linearRampToValueAtTime(f * 1.05, t + 1.3)
      const bp = ctx.createBiquadFilter(); bp.type = 'bandpass'; bp.frequency.value = 520; bp.Q.value = 3
      const g = ctx.createGain(); g.gain.setValueAtTime(0.0001, t); g.gain.exponentialRampToValueAtTime(0.035, t + 0.25); g.gain.exponentialRampToValueAtTime(0.0001, t + 1.4)
      o.connect(bp); bp.connect(g); g.connect(sfxBus); o.start(t + Math.random() * 0.08); o.stop(t + 1.5)
    }
  },
  laugh() { const t = T(); for (let i = 0; i < 7; i++) noise(t + i * 0.13 + Math.random() * 0.03, 0.1, { freq: 700 + Math.random() * 400, q: 4, gain: 0.07 }) },
  applause(sec = 2.8) {
    const t = T(); const n = Math.floor(sec * 70)
    for (let i = 0; i < n; i++) {
      const at = t + Math.random() * sec
      const fade = 1 - Math.max(0, (at - t) - sec * 0.6) / (sec * 0.4)
      noise(at, 0.03, { freq: 1100 + Math.random() * 1400, q: 1.5, gain: 0.05 * fade })
    }
  },
  fanfare() {
    const t = T()
    ;[[67, 0], [72, 0.13], [76, 0.26]].forEach(([m, d]) => brass([m], t + d, 0.12, 0.06))
    brass([72, 76, 79, 84], t + 0.4, 0.9, 0.055); kick(t + 0.4, 0.4, sfxBus); noise(t + 0.4, 1.4, { type: 'highpass', freq: 4000, gain: 0.14 })
  },
  countTick(step: number) { tone(1200 + step * 25, T(), 0.025, { type: 'square', gain: 0.025, lp: 4000 }) },
  whoosh() { noise(T(), 0.35, { freq: 400, sweepTo: 4000, q: 1.2, gain: 0.14, attack: 0.1 }) },
  pop() { const t = T(); tone(500, t, 0.08, { gain: 0.2, slideTo: 1200 }); noise(t, 0.05, { freq: 2500, gain: 0.1 }) },
  stamp() { const t = T(); kick(t, 0.3, sfxBus); noise(t, 0.08, { freq: 900, q: 0.8, gain: 0.25 }) },
  scratch() { const t = T(); noise(t, 0.12, { freq: 800, sweepTo: 3500, q: 4, gain: 0.25 }); noise(t + 0.12, 0.16, { freq: 3500, sweepTo: 600, q: 4, gain: 0.25 }) },
  // ---- casino table ----
  /** Clay chips set down: a quick double clack, pitched by stack size. */
  chipClack(step = 0) {
    const t = T(); const f = 3200 * Math.pow(2, Math.min(step, 12) / 24)
    ;[0, 0.045].forEach((d, i) => { noise(t + d, 0.025, { freq: f * (i ? 1.12 : 1) * jitter(0.03), q: 6, gain: 0.22 }); tone(f / 3, t + d, 0.02, { gain: 0.05 }) })
  },
  /** One card slid off the shoe. */
  cardFlick(step = 0) { const t = T(); noise(t, 0.06, { freq: 3800 + (step % 6) * 150, q: 2, sweepTo: 7000, gain: 0.16 }); noise(t + 0.05, 0.03, { freq: 900, q: 1, gain: 0.08 }) },
  /** The dealer turns the hole card. */
  cardFlip() { const t = T(); noise(t, 0.09, { freq: 2200, sweepTo: 5500, q: 1.5, gain: 0.2 }); kick(t + 0.07, 0.16, sfxBus) },
  jackpot() {
    const t = T()
    ;[72, 76, 79, 84, 88, 91, 96].forEach((m, i) => { tone(midi(m), t + i * 0.07, 0.4, { gain: 0.13 }); tone(midi(m) * 2.76, t + i * 0.07, 0.1, { gain: 0.04 }) })
    for (let i = 0; i < 26; i++) noise(t + 0.3 + Math.random() * 1.4, 0.05, { type: 'highpass', freq: 6000 + Math.random() * 3000, gain: 0.07 })
    brass([72, 76, 79], t + 0.5, 0.7, 0.05)
  },
  bust() {
    const t = T(); noise(t, 0.45, { type: 'highpass', freq: 2500, gain: 0.3 })
    tone(330, t, 0.5, { type: 'square', gain: 0.07, slideTo: 90, lp: 1600 })
  },
  /** Funky little brass lick for winning hands. */
  winSting() { const t = T(); [[65, 0], [69, 0.09], [72, 0.18], [75, 0.27], [76, 0.34]].forEach(([m, d]) => brass([m], t + d, d === 0.34 ? 0.5 : 0.08, 0.06)); kick(t + 0.34, 0.3, sfxBus) },
  /** Everyone lost: a sad guitar slide down. */
  loseSting() {
    const t = T()
    ;[[64, 0], [63, 0.3], [62, 0.6]].forEach(([m, d]) => tone(midi(m) / 2, t + d, 0.26, { type: 'sawtooth', gain: 0.1, lp: 1300, attack: 0.01 }))
    tone(midi(61) / 2, t + 0.9, 1.1, { type: 'sawtooth', gain: 0.1, lp: 1000, slideTo: midi(56) / 2 })
  },
  /** Chips pushed across the felt to a winner. */
  payout(n = 8) { const t = T(); for (let i = 0; i < n; i++) noise(t + i * 0.04 + Math.random() * 0.015, 0.025, { freq: 3000 + Math.random() * 1200, q: 5, gain: 0.12 }) },
  resume() { const t = T(); [0, 0.08, 0.16].forEach((d, i) => tone(midi(72 + penta[i + 2]), t + d, 0.15, { type: 'triangle', gain: 0.14 })) },
}


/** Every effect the show plays. Sample ids match controller/scripts/audio/cues.json. */
export const sfx = {
  focus: () => play('focus', {}, synth.focus),
  select: () => play('select', {}, synth.select),
  back: () => play('back', {}, synth.back),
  /** A contestant joins: one step higher each time. */
  join: (step: number) => play('join', { rate: semis(PENTA_SEMIS[step % 10]) }, () => synth.join(step)),
  leave: () => play('leave', {}, synth.leave),
  /** A bluff, bet or vote is in: climbs with progress. */
  chip: (step: number) => play('vote', { rate: semis(Math.min(step, 12)) }, () => synth.chip(step)),
  vote: (step: number) => play('vote', { rate: semis(Math.min(step, 12)) }, () => synth.chip(step)),
  deal: (step: number) => play('card', { rate: semis(step % 6) }, () => synth.deal(step)),
  ding: () => play('ding', {}, synth.ding),
  allIn: () => { duck(0.3, 0.8); play('allIn', {}, synth.allIn) },
  buzzer: () => { duck(0.3, 0.8); play('buzzer', {}, synth.buzzer) },
  tick: (secondsLeft: number) => play('tick', { rate: secondsLeft <= 3 ? semis((3 - secondsLeft) * 2) : 1 }, () => synth.tick(secondsLeft)),
  roundStart: (final = false) => { duck(0.25, 1.8); play(final ? 'finalRound' : 'roundStart', {}, () => synth.roundStart(final)) },
  showOpen: () => { duck(0.25, 2); play('showOpen', {}, synth.showOpen) },
  drumroll: (sec = 1.6) => play('drumroll', {}, () => synth.drumroll(sec)),
  crash: () => play('crash', {}, synth.crash),
  womp: () => { duck(0.4, 1.4); play('womp', {}, synth.womp) },
  ooh: (size: number) => play('ooh', { gain: Math.min(1, 0.5 + size * 0.1) }, () => synth.ooh(size)),
  laugh: () => play('laugh', {}, synth.laugh),
  applause: (sec = 2.8) => play('applause', { gain: Math.min(1, sec / 3) }, () => synth.applause(sec)),
  fanfare: () => { duck(0.25, 2.2); play('fanfare', {}, synth.fanfare) },
  countTick: (step: number) => play('countTick', { rate: semis(step % 12), gain: 0.5 }, () => synth.countTick(step)),
  whoosh: () => play('whoosh', {}, synth.whoosh),
  pop: () => play('pop', {}, synth.pop),
  stamp: () => play('stamp', {}, synth.stamp),
  scratch: () => { duck(0.2, 1); play('scratch', {}, synth.scratch) },
  chipClack: (step = 0) => play('chipClack', { rate: semis(Math.min(step, 12) / 2) }, () => synth.chipClack(step)),
  cardFlick: (step = 0) => play('card', { rate: semis(step % 6) }, () => synth.cardFlick(step)),
  cardFlip: () => play('cardFlip', {}, synth.cardFlip),
  jackpot: () => { duck(0.3, 1.8); play('jackpot', {}, synth.jackpot) },
  bust: () => play('bust', {}, synth.bust),
  winSting: () => { duck(0.3, 1.4); play('winSting', {}, synth.winSting) },
  loseSting: () => { duck(0.3, 1.6); play('loseSting', {}, synth.loseSting) },
  payout: (n = 8) => play('payout', {}, () => synth.payout(n)),
  resume: () => play('resume', {}, synth.resume),
  // ---- Brain Drain ----
  correct: () => { duck(0.3, 1.4); play('correct', {}, synth.fanfare) },
  wrong: () => { duck(0.35, 1.4); play('wrong', {}, synth.womp) },
  steal: () => { duck(0.3, 1.6); play('steal', {}, () => { synth.whoosh(); synth.payout(14) }) },
  drinkCall: () => { duck(0.3, 1.6); play('drinkCall', {}, () => { synth.ding(); synth.stamp() }) },
  boing: () => play('boing', {}, synth.pop),
  // ---- Home Turf (each falls back to an existing sample until its own cue is generated) ----
  diceRoll: () => play('diceRoll', {}, () => { play('chipClack', { rate: semis(4) }, () => synth.chipClack(4)); play('chipClack', { delay: 0.09, rate: semis(7) }) }),
  /** A piece hops one space: climbs a scale as it goes. */
  hop: (step: number) => play('hop', { rate: semis(PENTA_SEMIS[step % 10]), gain: 0.7 }, () => play('pop', { rate: semis(PENTA_SEMIS[step % 10]), gain: 0.6 }, synth.pop)),
  gavel: () => { duck(0.3, 1); play('gavel', {}, () => play('stamp', {}, synth.stamp)) },
  jailClang: () => { duck(0.3, 1.2); play('jailClang', {}, () => play('bust', {}, synth.bust)) },
  hammer: () => play('hammer', {}, () => play('stamp', { rate: semis(5), gain: 0.7 }, synth.stamp)),
  register: () => play('register', {}, () => play('payout', {}, () => synth.payout(6))),
  payday: () => play('payday', {}, () => play('payout', {}, () => synth.payout(8))),
  homeTurf: () => { duck(0.3, 2); play('homeTurf', {}, () => play('jackpot', {}, synth.jackpot)) },
  bankruptSting: () => { duck(0.25, 2.4); play('bankruptSting', {}, () => { play('crash', {}, synth.crash); play('womp', {}, synth.womp) }) },
  lastLap: () => { duck(0.25, 2); play('lastLap', {}, () => play('finalRound', {}, () => synth.roundStart(true))) },
  couch: () => play('couch', {}, () => play('boing', {}, synth.pop)),
  busHorn: () => play('busHorn', {}, () => play('whoosh', {}, synth.whoosh)),
  dealDone: () => { duck(0.3, 1.6); play('dealDone', {}, () => { play('stamp', {}, synth.stamp); play('applause', {}, () => synth.applause(1.8)) }) },
  offerPing: () => play('offerPing', {}, () => play('ding', {}, synth.ding)),
  soldTag: () => play('soldTag', {}, () => play('stamp', {}, synth.stamp)),
  cardDraw: () => play('cardDraw', {}, () => play('cardFlip', {}, synth.cardFlip)),
  // ---- Sprawl (each falls back to an existing sample until its own cue is generated) ----
  landlord: () => { duck(0.3, 1.6); play('landlord', {}, () => play('steal', {}, () => { synth.whoosh(); synth.payout(14) })) },
  /** Resources pour in after a roll: brighter the more that arrived. */
  harvest: (n = 1) => play('harvest', { rate: semis(Math.min(n, 8)) }, () => play('payday', { gain: 0.7 }, () => synth.payout(4 + n))),
  settle: () => play('settle', {}, () => play('hammer', { rate: semis(-3) }, synth.stamp)),
  cityUp: () => { duck(0.3, 1.4); play('cityUp', {}, () => play('fanfare', {}, synth.fanfare)) },
  longRoad: () => { duck(0.3, 1.8); play('longRoad', {}, () => play('homeTurf', {}, () => play('jackpot', {}, synth.jackpot))) },
  bigCrew: () => { duck(0.3, 1.8); play('bigCrew', {}, () => play('homeTurf', {}, () => play('jackpot', {}, synth.jackpot))) },
  sprawlWin: () => { duck(0.2, 3); play('sprawlWin', {}, () => play('fanfare', {}, synth.fanfare)) },
}

const PENTA_SEMIS = [0, 2, 4, 7, 9, 12, 14, 16, 19, 21]

// ---------- music ----------

export type Mode = 'off' | 'lobby' | 'teamup' | 'quick' | 'ballpark' | 'sides' | 'heist' | 'gauntlet' | 'standings' | 'podium'
  | 'bluff' | 'reveal' | 'scores' | 'casino' | 'turf' | 'auction' | 'lastlap' | 'sprawl'
/** Modes whose own loop may not be generated yet borrow another one meanwhile. */
const MUSIC_FALLBACK: Partial<Record<Mode, Mode>> = { turf: 'lobby', auction: 'heist', lastlap: 'gauntlet', sprawl: 'turf' }
let want: Mode = 'off'
let hurry = false
let current: { mode: string; src: AudioBufferSourceNode; gain: GainNode } | null = null

/** Picks the loop for a phase; modes without a track fall silent. */
export function setMusic(m: Mode) { if (m === want) return; want = m; retune() }
/** Last ten seconds: crossfade to the hurry-up bed if there is one. */
export function setHurry(h: boolean) { if (h === hurry) return; hurry = h; retune() }

function retune() {
  if (!ctx) return
  const target = hurry && musicBank.has('hurry') && ['quick', 'ballpark', 'heist', 'gauntlet', 'bluff', 'sides'].includes(want) ? 'hurry' : want
  if (current?.mode === target) return
  const t = ctx.currentTime
  const fade = 1.2
  if (current) {
    const old = current
    old.gain.gain.cancelScheduledValues(t)
    old.gain.gain.setValueAtTime(old.gain.gain.value, t)
    old.gain.gain.linearRampToValueAtTime(0.0001, t + fade)
    old.src.stop(t + fade + 0.05)
    current = null
  }
  const entry = musicBank.get(target) ?? musicBank.get(MUSIC_FALLBACK[target as Mode] ?? '')
  if (!entry || target === 'off') return
  const src = ctx.createBufferSource()
  src.buffer = entry.buf
  src.loop = true
  if (entry.track.loopStart != null) src.loopStart = entry.track.loopStart
  if (entry.track.loopEnd != null) src.loopEnd = entry.track.loopEnd
  const gain = ctx.createGain()
  gain.gain.setValueAtTime(0.0001, t)
  gain.gain.linearRampToValueAtTime(entry.track.gain ?? 1, t + fade)
  src.connect(gain); gain.connect(duckBus)
  src.start(t)
  current = { mode: target, src, gain }
}
